.PHONY : all clean

all:
	g++ -o bai1 bai1.cpp
	g++ -o bai2 bai2.cpp
	g++ -o bai3 bai3.cpp
	g++ -o bai4 bai4.cpp
	g++ -o bai6 bai6.cpp
	g++ -o bai7 bai7.cpp
	g++ -o bai8 bai8.cpp
	g++ -o bai9 bai9.cpp
	g++ -o bai10 bai10.cpp
	g++ -o bai11 bai11.cpp
	g++ -o bai12 bai12.cpp
	g++ -o bai13 bai13.cpp
clean:
	rm -rf bai1 bai2 bai3 bai4 bai6 bai7 bai8 bai9 bai10 bai11 bai12 bai13