.PHONY : all clean

all:
	g++ -o bai14 bai14.cpp
	g++ -o bai15 bai15.cpp
	g++ -o bai16 bai16.cpp
	g++ -o bai17 bai17.cpp
	g++ -o bai18 bai18.cpp
	g++ -o bai19 bai19.cpp
	g++ -o bai20 bai20.cpp
	g++ -o bai21 bai21.cpp
	g++ -o bai22 bai22.cpp
	g++ -o bai23 bai23.cpp
clean:
	rm bai14 bai15 bai16 bai17 bai18 bai19 bai20 bai21 bai22 bai23
