.PHONY : all clean

all:
	g++ -o bai14 bai14.cpp
	g++ -o bai15 bai15.cpp
	g++ -o bai16 bai16.cpp
	g++ -o bai17 bai17.cpp
	g++ -o bai18 bai18.cpp
	g++ -o bai19 bai19.cpp
	g++ -o bai20 bai20.cpp
	g++ -o bai21 bai21.cpp
	g++ -o bai22 bai22.cpp
	g++ -o bai23 bai23.cpp
	g++ -o bai24 bai24.cpp
	g++ -o bai25 bai25.cpp
	g++ -o bai26 bai26.cpp
	g++ -o bai27 bai27.cpp
	g++ -o bai28 bai28.cpp
	g++ -o bai29 bai29.cpp
clean:
	rm bai14 bai15 bai16 bai17 bai18 bai19 bai20 bai21 bai22 bai23 bai24 bai25 bai26 bai27 bai28 bai29
